# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 908d966b760e37bacf1711d66ccbefa817a5658122259486667126a00836f6dc715d0444db213320fbc775341c81196b05f20fef60f5b10fcca16a0fac2ddeaf

test:
  secret_key_base: eef369c8071a49060e54d8fcb6cd94ce5b13da3c944cd149c857d168de77714243379aa807dd97f6713fb092358e83f2db9fcf6a1085bd59f82de0c8b6d5d980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
